spring.application.name=notification-service
server.port=8082

# Mail Configuration (Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:YOUR_EMAIL@gmail.com}
spring.mail.password=${MAIL_PASSWORD:YOUR_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Tracing
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.tracing.propagation.type=w3c
